# Note: I recommend (and have used): https://www.composerize.com/
name: amml-python-base
services:
  amml-python-base-cpu:
    build:
      args:
        hardware: cpu
      target: full
    image: amml-python-base-cpu:latest
    stdin_open: true
    tty: true
    command: bash
  amml-python-base-cpu-slim:
    build:
      args:
        hardware: cpu
      target: slim
    image: amml-python-base-cpu-slim:latest
    stdin_open: true
    tty: true
    command: bash
  amml-python-base-cuda:
    build:
      args:
        hardware: cuda
      target: full
    # See: https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/running.html
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    stdin_open: true
    tty: true
    image: amml-python-base-cuda:latest
  amml-python-base-cuda-slim:
    build:
      args:
        hardware: cuda
      target: slim
    # See: https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/running.html
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    stdin_open: true
    tty: true
    image: amml-python-base-cuda-slim:latest